# Generated by Django 2.2 on 2020-04-26 13:19

import api.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(default='Paris', max_length=255)),
                ('opened', models.IntegerField(default=2020)),
                ('is_virtual', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
            managers=[
                ('virtual_galleries', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Sculpture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('published', models.IntegerField(default=2020)),
                ('material', models.CharField(default='Stone', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sculptures', validators=[api.validators.validate_file_size, api.validators.validate_extension])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sculptures', to='api.Gallery')),
            ],
            options={
                'verbose_name': 'Sculpture',
                'verbose_name_plural': 'Sculptures',
            },
            managers=[
                ('created_by_user', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('published', models.IntegerField(default=2020)),
                ('genre', models.CharField(default='Landscape', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures', validators=[api.validators.validate_file_size, api.validators.validate_extension])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='api.Gallery')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
            managers=[
                ('created_by_user', django.db.models.manager.Manager()),
            ],
        ),
    ]
