# Generated by Django 3.0.5 on 2020-04-23 19:05

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('year_of_opening', models.IntegerField(default=None)),
                ('is_virtual', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_of_publishing', models.IntegerField(blank=True, default=None, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='pictures', validators=[utils.validators.validate_file_size, utils.validators.validate_extension])),
                ('gallery', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='api.Gallery')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
        ),
    ]
