# Generated by Django 2.2 on 2020-04-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gallery',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='picture',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='sculpture',
            managers=[
            ],
        ),
    ]
