# Generated by Django 3.0.5 on 2020-04-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_virtual',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
