# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-14 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='virtual',
            new_name='is_virtual',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='year',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='year',
        ),
        migrations.AddField(
            model_name='gallery',
            name='date_of_opening',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='gallery',
            name='picture',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Picture'),
        ),
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(default=None, upload_to=b''),
        ),
        migrations.AddField(
            model_name='picture',
            name='year_of_publishing',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
