# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-15 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200414_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='date_of_opening',
        ),
        migrations.AddField(
            model_name='gallery',
            name='year_of_opening',
            field=models.IntegerField(default=None),
        ),
    ]
