# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-17 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200415_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'pictures', validators=[utils.validators.validate_file_size, utils.validators.validate_extension]),
        ),
    ]
